name: CTF
version: 1.0
description: This plugin is to play ctf

author: Intelligent_Cake

main: com.intelligentcake.ctf.CTF
api-version: 1.17

commands:
  team:
    description: This is CTF Commands.
    aliases: [ctfteam]
    usage: /ctfteam