name: CTF
version: 0.2.1
description: This plugin is to play ctf

author: Intelligent_Cake

main: com.intelligentcake.ctf.CTF

commands:
  ctf:
    description: This is CTF Commands.
    aliases: [ctf]
    permission: ctf.ctf
    usage: /ctf